name: church_control
description: App for control your church.
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+10

environment:
  sdk: ">=2.18.6 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_modular: ^3.2.2+1
  mobx: ^2.0.7+5
  flutter_mobx: ^2.0.0
  dio: ^4.0.4
  shared_preferences: ^2.0.6
  string_validator: ^0.3.0
  dartz: ^0.10.1
  hexcolor: ^2.0.4
  intl: ^0.17.0
  brasil_fields: ^1.5.0
  multi_select_flutter: ^4.1.2
  flutter_svg: ^1.1.6
  firebase_messaging: ^14.7.10
  firebase_core: ^2.5.0
  path: ^1.8.0
  image_picker: ^0.8.4
  image_picker_web: ^3.0.0+1
  image: ^4.0.15
  isolated_worker: ^0.1.1
  firebase_crashlytics: ^3.3.2
  infinite_scroll_pagination: ^4.0.0
  multiselect: ^0.0.1
  csv: ^6.0.0
  file_saver: ^0.2.6
  another_flushbar: ^1.12.29

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.3.3
  mobx_codegen: ^2.0.1+3
  build_web_compilers: ^3.2.7
  flutter_launcher_icons: "^0.12.0"
  change_app_package_name: ^1.1.0

dependency_overrides:
  intl: ^0.17.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/fonts/
  fonts:
    - family: Lato
      fonts:
        - asset: assets/fonts/Lato-Black.ttf
        - asset: assets/fonts/Lato-BlackItalic.ttf
        - asset: assets/fonts/Lato-Bold.ttf
        - asset: assets/fonts/Lato-BoldItalic.ttf
        - asset: assets/fonts/Lato-Italic.ttf
        - asset: assets/fonts/Lato-Light.ttf
        - asset: assets/fonts/Lato-LightItalic.ttf
        - asset: assets/fonts/Lato-Regular.ttf
        - asset: assets/fonts/Lato-Thin.ttf
        - asset: assets/fonts/Lato-ThinItalic.ttf
        
flutter_icons:
  image_path: "assets/images/logo_vila_yara.jpg"
  android: true
  ios: true
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/images/logo_vila_yara.jpg"
    background_color: "#F1F2F0"
    theme_color: "#F1F2F0"