// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBpFyYO3FrJM1sf_rdSuJMvPxgD5zo4T9Y',
    appId: '1:321544719651:web:501a92df185514195f9096',
    messagingSenderId: '321544719651',
    projectId: 'church-control-28e53',
    authDomain: 'church-control-28e53.firebaseapp.com',
    storageBucket: 'church-control-28e53.appspot.com',
    measurementId: 'G-YN85BMCE9T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyACgeRHld1EXdWemcLuIirziCEojhnrgb0',
    appId: '1:321544719651:android:97bc09f6f0cbc8735f9096',
    messagingSenderId: '321544719651',
    projectId: 'church-control-28e53',
    storageBucket: 'church-control-28e53.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBh54eg2zd0ecgo392PlaeJWhk_4ywBhwI',
    appId: '1:321544719651:ios:ff91fa367fd32b8c5f9096',
    messagingSenderId: '321544719651',
    projectId: 'church-control-28e53',
    storageBucket: 'church-control-28e53.appspot.com',
    iosClientId: '321544719651-io3muk009vt0k47lc82gqjit1jkpkqem.apps.googleusercontent.com',
    iosBundleId: 'com.example.churchControl',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBh54eg2zd0ecgo392PlaeJWhk_4ywBhwI',
    appId: '1:321544719651:ios:ff91fa367fd32b8c5f9096',
    messagingSenderId: '321544719651',
    projectId: 'church-control-28e53',
    storageBucket: 'church-control-28e53.appspot.com',
    iosClientId: '321544719651-io3muk009vt0k47lc82gqjit1jkpkqem.apps.googleusercontent.com',
    iosBundleId: 'com.example.churchControl',
  );
}
